---
- name: Install redis server
  apt: pkg=redis-server
  
- name: Copy redis config
  copy: src={{item}} dest=/etc/redis
  with_items:
  - redis.conf
  - persist.conf
  - evict.conf
  notify: restart redis

- name: Port rules
  command: ufw allow {{item}}
  with_items:
  - 6379
  - 6380
