---
- name: Install nagios3
  apt: pkg=nagios3

- name: Copy conf.d
  copy: src={{item}} dest=/etc/nagios3/conf.d
  with_fileglob:
  -  ./conf.d/*
  notify: Restart nagios3

- name: Copy main config
  copy: src={{item}} dest=/etc/nagios3
  with_items:
  -  cgi.cfg
  -  commands.cfg
  -  nagios.cfg
  notify: Restart nagios3

- name: Set firewall rules
  command: ufw allow {{item}}
  with_items:
    - http/tcp
    - https/tcp
  register: ufw_result
  changed_when: "'Rule added' in ufw_result.stdout"

- name: Install nrpe plugin
  apt: pkg=nagios-nrpe-plugin
