language: php
php:
  - 5.4

before_install:
  - sudo FORCE_ADD_APT_REPOSITORY=1 add-apt-repository ppa:rquillo/ansible
  - sudo apt-get update

install:
  - sudo apt-get install ansible

script:
  # Check playbook syntax
  - ansible-playbook -i production local.yml --syntax-check
  # Check php script syntax
  - php -l roles/mediawiki/files/LocalSettings.php.j2
  - php -l roles/mediawiki/files/StartProfiler.php

notifications:
  irc:
    channels:
      - "chat.freenode.net#orain"
    on_success: change
    on_failure: always
  email:
    recipients:
      - addshorewiki@gmail.com
    on_success: change
    on_failure: always