---
# python may need to be installed manually.
- hosts: all
  vars_files:
    - ../orain_private/vars.yml
  roles:
    - common

- hosts: mediawikiservers
  vars_files:
    - ../orain_private/vars.yml
  roles:
    - nginx
    - php
    - memcached
    - mediawiki

- hosts: dbservers
  vars_files:
    - ../orain_private/vars.yml
  roles:
    - mariadb

- hosts: monitoringservers
  vars_files:
    - ../orain_private/vars.yml
  roles:
    - nagios
