- name: Copy HAProxy config
  template: src="haproxy.cfg" dest=/etc/haproxy/haproxy.cfg
  notify: Restart HAProxy

- name: Copy pem files
  copy: src=/root/private/ssl/Orain_GlobalSign_2014.pem dest=/etc/ssl/private/Orain_GlobalSign_2014.pem
