- name: Copy HHVM fastcgi script to init.d
  copy: src="hhvm" dest=/etc/init.d/hhvm owner=root group=root mode=770

- name: Add hhvm to boot
  command: update-rc.d hhvm defaults 98
  register: update_rc_hhvm
  failed_when: "'error' in update_rc_hhvm.stdout"
  changed_when: False # never report as "changed"

- name: Copy config.hdf over
  template: src="config.hdf" dest=/etc/hhvm/config.hdf owner=root group=root mode=644
