- name: Create user "{{user}}"
  user: name={{user}} group={{group}} shell=/bin/zsh

- name: Upload {{user}}'s public key
  authorized_key: user={{user}} key="{{ lookup('file', './ssh/' ~ user ~ '.pub') }}"
