---
- name: Install ansible dependencies
  raw: apt-get install -y python-apt python-simplejson

- name: Install packages
  apt: pkg={{item}}
  with_items:
    - denyhosts
    - fail2ban
    - ferm
    - git
    - htop
    - lsof
    - lynis
    - mosh
    - mysql-client
    - nano
    - netcat
    - python3
    - python3-requests
    - python-software-properties
    - rkhunter
    - systemd
    - tmux
    - vim
    - zip
    - zsh

# Hacks to force systemd-sysv to install and stay installed
- name: Force-install systemd-sysv
  raw: yes 'Yes, do as I say!' | apt-get install --force-yes systemd-sysv

- name: Hold systemd-sysv
  shell: echo systemd-sysv hold | dpkg --set-selections

# Don't edit without validating first
- name: Allow users in the sudo group to run sudo without a password
  lineinfile: dest=/etc/sudoers
              regexp='^\%sudo'
              line='%sudo ALL=(ALL) NOPASSWD:ALL'

- include: create_user.yml user={{item.name}} group={{item.group}}
  with_items:
    - { name: 'kudu', group: 'sudo' }
    - { name: 'addshore', group: 'sudo' }
    - { name: 'johnflewis', group: 'sudo' }

- name: Create user "www-scripts"
  user: name=www-scripts group=www-data shell=/bin/zsh

- name: Copy ferm firewall rules
  copy: src=ferm.conf dest=/etc/ferm/ferm.conf
  notify:
    - Reload ferm

- name: Copy backup.sh
  template: src=backup.sh dest=/root/backup.sh

- name: Create a cronjob for backup.sh
  cron: name="backup.sh"
        user="root"
        minute=0
        hour=0
        job="/root/backup.sh > /var/log/backup.log 2>&1"

- name: Copy ansible logrotate configuration
  copy: src="./logrotate.d/ansible" dest=/etc/logrotate.d
