- name: Install ansible dependencies
  raw: apt-get install -y python-apt python-simplejson

- name: Update Apt Cache (on the hour)
  apt: update_cache=yes cache_valid_time=3600

- name: Install packages
  apt: pkg={{item}}
  with_items:
    - aptitude
    - denyhosts
    - fail2ban
    - lsof
    - lynis
    - nagios-nrpe-server
    - python3
    - python-software-properties
    - rkhunter
    - sudo
    - tmux
    - ufw
    - zsh

- name: Install packages (latest)
  apt: pkg={{item}} state=latest
  with_items:
    - git
    - htop
    - mysql-client # Needed for testing mysql connectivity between instance - Addshore
    - mosh
    - nano
    - netcat
    - vim
    - zip

# Don't edit without validating first
- name: Allow users in the sudo group to run sudo without a password
  lineinfile: dest=/etc/sudoers
              regexp='^\%sudo'
              line='%sudo ALL=(ALL) NOPASSWD:ALL'

- include: create_user.yml

- name: Create log directories
  command: mkdir -p {{item}}
  with_items:
    - /var/log/cron/
  changed_when: False # never report as "changed"

- name: Copy backup.sh
  template: src=backup.sh dest=/root/backup.sh  owner=root group=root mode=770

- name: Create a cronjob for backup.sh
  cron: name="backup.sh"
        user="root"
        minute=0
        hour=0
        job="/root/backup.sh > /var/log/cron/backup.log 2>&1"

- name: Copy ansible logrotate configuration
  copy: src="./logrotate.d/ansible" dest=/etc/logrotate.d

- name: Copy quickscripts
  template: src={{item}} dest=/root/{{item|basename}} owner=root group=root mode=770
  with_fileglob:
    - ./quickscripts/*

- name: Create a cronjob for auto running of ansible
  cron: name="Automatic Run"
        user="root"
        minute=*/10
        job="/root/ans-all  > /var/log/ans-all.log 2>&1"

- name: Copy default ufw default settings
  copy: src="./ufw/default" dest=/etc/default/ufw

- name: Copy ufw files
  copy: src=./ufw/{{item}} dest=/etc/ufw/{{item|basename}} owner=root group=root mode=700
  with_items:
    - after.rules
    - before.rules

- name: Set firewall rules
  command: ufw allow {{item}}
  with_items:
    - ssh/tcp
    - 60000:61000/udp
    - 53/tcp
    - 53/udp
    - 7001
    - 5666
  register: ufw_result
  changed_when: "'Rule added' in ufw_result.stdout"

- name: Check status of ufw
  command: ufw status
  register: ufw_status
  changed_when: False # never report as "changed"

- name: Check config of ufw
  command: cat /etc/ufw/ufw.conf
  register: ufw_config
  changed_when: False # never report as "changed"

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=664748
- name: Disable logging (workaround for known bug in Debian 7)
  command: ufw logging off
  when: "ansible_lsb['codename'] == 'wheezy' and 'LOGLEVEL=off' not in ufw_config.stdout"

- name: Enable ufw
  command: ufw --force enable
  when: "ufw_status.stdout.startswith('Status: inactive') or 'ENABLED=yes' not in ufw_config.stdout"

- name: Create user "nagios"
  user: name=nagios shell=/bin/zsh

- name: Install nrpe plugin
  apt: pkg=nagios-nrpe-plugin

- name: Copy nagios plugins over
  copy: src={{item}} dest=/usr/lib/nagios/plugins/
  with_fileglob:
  -  ./plugins/*

- name: Copy nrpe_local.cfg to remote servers
  copy: src=nrpe_local.cfg dest=/etc/nagios
  notify: Restart nrpe

- name: Copy nrpe.cfg to remote servers
  copy: src=nrpe.cfg dest=/etc/nagios
  notify: Restart nrpe
