# Don't edit without validating first
- name: Allow users in the sudo group to run sudo without a password
  lineinfile: dest=/etc/sudoers
              regexp='^\%sudo'
              line='%sudo ALL=(ALL) NOPASSWD:ALL'

- name: Create user "{{item.name}}"
  user: name={{item.name}} groups={{item.groups}} shell=/bin/zsh
  with_items: users

- name: Upload {{item.name}}'s public key
  authorized_key: user={{item.name}} key="{{ lookup('file', './ssh/' ~ item.name ~ '.pub') }}"
  with_items: users

