- name: Rebuild localisation cache
  command: /usr/bin/php /srv/mediawiki/w/maintenance/rebuildLocalisationCache.php --wiki {{item}}
  sudo: yes
  sudo_user: mediawiki
  with_items:
#    - metawiki # Only uncomment this if things break
    - extloadwiki

- name: Clear APC cache
  command: /usr/bin/wget -qO- {{apc_clear_script}}
  sudo: yes
  sudo_user: mediawiki
  register: clear_apc_cache
  failed_when: clear_apc_cache.stdout.find('true') == -1

- name: Install Validator dependencies using Composer
  shell: "cd /srv/mediawiki/w/extensions/Validator && /usr/bin/composer.phar install"
  sudo: yes
  sudo_user: mediawiki

- name: Mediawiki submodule fileMode false
  shell: "cd /srv/mediawiki/w/ && git submodule foreach --recursive git config core.fileMode false"
  sudo: yes
  sudo_user: mediawiki

- name: Update mediawiki
  shell: "/root/mw-updateall"
