- name: Download {{item}}
  command: git submodule update extensions/{{item}}
           chdir=/usr/share/nginx/.orain.org/w

# Hacky, should be rewritten
- name: Check out new stable {{item}} branch
  command: git checkout -b {{version}} origin/{{version}}
           chdir=/usr/share/nginx/.orain.org/w/extensions/{{item}}
  register: result
  ignore_errors: True

- name: Check out existing stable {{item}} branch
  command: git checkout {{version}}
           chdir=/usr/share/nginx/.orain.org/w/extensions/{{item}}
  when: result|failed
