---
- name: Check out latest stable WMF branch of MediaWiki
  git: repo=https://gerrit.wikimedia.org/r/p/mediawiki/core.git
       dest=/usr/share/nginx/.orain.org/w
       version=origin/wmf/1.22wmf10

- name: Copy MediaWiki settings from templates
  template: src={{item}} dest=/usr/share/nginx/.orain.org/w/{{item|basename|replace('.j2','')}} backup=yes
  with_fileglob:
    - ./*.php.j2
  notify: Clear APC cache

- name: Copy MediaWiki settings from files
  copy: src={{item}} dest=/usr/share/nginx/.orain.org/w/{{item|basename}} backup=yes
  with_fileglob:
    - ./*.php
  notify: Clear APC cache

- name: Copy Bad Behavior settings
  template: src=./settings.ini.j2 dest=/usr/share/nginx/.orain.org/w/extensions/bad-behavior/settings.ini backup=yes
  notify: Clear APC cache

- name: Download MediaWiki extensions
  command: git submodule update --init extensions/{{item}}
           chdir=/usr/share/nginx/.orain.org/w
  with_items:
    - AbuseFilter
    - AntiSpoof
    - CentralAuth
    - CheckUser
    - ConfirmEdit
    - GlobalBlocking
    - InputBox
    - Nuke
    - ParserFunctions
    - Renameuser
    - Scribunto
    - SiteMatrix
    - SpamBlacklist
    - TitleBlacklist
    - WikimediaMessages

- name: Patch CentralAuth group name
  lineinfile: dest=/usr/share/nginx/.orain.org/w/extensions/CentralAuth/CentralAuth.i18n.php
              regexp="\s*'centralauth-groupname'\s*=> 'the Wikimedia Foundation'",
              state=absent
              backup=yes
