---
- name: Check out latest stable WMF branch of MediaWiki
  git: repo=https://github.com/Orain/mediawiki-core.git
       dest=/usr/share/nginx/.orain.org/w
       version=wmf/1.22wmf12

- name: Copy MediaWiki settings from templates
  template: src={{item}} dest=/usr/share/nginx/.orain.org/w/{{item|basename|replace('.j2','')}} backup=yes
  with_fileglob:
    - ./*.php.j2
  notify: Clear APC cache

- name: Copy MediaWiki settings from files
  copy: src={{item}} dest=/usr/share/nginx/.orain.org/w/{{item|basename}} backup=yes
  with_fileglob:
    - ./*.php
  notify: Clear APC cache

- name: Copy get_db_list.py
  copy: src=get_db_list.py dest=/home/www-scripts/get_db_list.py owner=www-scripts group=www-data mode=770 backup=yes

- name: Create a crontab for get_db_list.py
  cron: name="Get DB list" user="www-scripts" job="python ~/get_db_list.py"

- name: Download MediaWiki extensions
  command: >
            git submodule update --init
            extensions/AbuseFilter
            extensions/AdminLinks
            extensions/AntiSpoof
            extensions/ApiSandbox
            extensions/Babel
            extensions/CategoryTree
            extensions/CentralAuth
            extensions/CharInsert
            extensions/CheckUser
            extensions/Cite
            extensions/CodeEditor
            extensions/Comments
            extensions/CreateBox
            extensions/CreateWiki
            extensions/ConfirmEdit
            extensions/Disambiguator
            extensions/DPLforum
            extensions/Gadgets
            extensions/GlobalBlocking
            extensions/HeaderTabs
            extensions/ImageMap
            extensions/InputBox
            extensions/intersection
            extensions/Interwiki
            extensions/InterwikiMagic
            extensions/LabeledSectionTransclusion
            extensions/LiquidThreads
            extensions/MyVariables
            extensions/Nuke
            extensions/ParserFunctions
            extensions/Poem
            extensions/Quiz
            extensions/RandomSelection
            extensions/Renameuser
            extensions/ReplaceText
            extensions/Scribunto
            extensions/SectionHide
            extensions/SimpleAntiSpam
            extensions/SiteMatrix
            extensions/SkinPerPage
            extensions/SpamBlacklist
            extensions/SyntaxHighlight_GeSHi
            extensions/Tabber
            extensions/TemplateSandbox
            extensions/TitleBlacklist
            extensions/Translate
            extensions/UniversalLanguageSelector
            extensions/Variables
            extensions/Vector
            extensions/WikiEditor
            extensions/WikimediaMessages
            skins/foreground
            skins/monaco
            chdir=/usr/share/nginx/.orain.org/w
