---
- name: Check out latest stable WMF branch of MediaWiki
  git: repo=https://github.com/Orain/mediawiki-core.git
       dest=/usr/share/nginx/.orain.org/w
       version=wmf/1.22wmf22

- name: Copy MediaWiki settings from templates
  template: src={{item}} dest=/usr/share/nginx/.orain.org/w/{{item|basename|replace('.j2','')}} backup=yes
  with_fileglob:
    - ./*.php.j2
  notify: Clear APC cache

- name: Copy MediaWiki settings from files
  copy: src={{item}} dest=/usr/share/nginx/.orain.org/w/{{item|basename}} backup=yes
  with_fileglob:
    - ./*.php
  notify: Clear APC cache

- name: Copy {{item}}
  copy: src={{item}} dest=/home/www-scripts owner=www-scripts group=www-data mode=770 backup=yes
  with_items:
    - get_db_list.py
    - db_loop.sh

- name: Copy logrotate configuration
  copy: src="./logrotate.d/mediawiki" dest=/etc/logrotate.d

- name: Create a cronjob for get_db_list.py
  cron: name="Get DB list" user="www-scripts" job="python3 ~/get_db_list.py"

- name: Create a cronjob for the MediaWiki job queue
  cron: name="MediaWiki job queue"
        user="www-scripts"
        minute=0
        job="~/db_loop.sh /usr/share/nginx/.orain.org/w/maintenance/runJobs.php > /var/log/mediawiki/runJobs.log 2>&1"

- name: Create a cronjob for MediaWiki localisation cache updating
  cron: name="MediaWiki localisation cache updating"
        user="www-scripts"
        minute=0
        hour="/6"
        job="/usr/bin/php /usr/share/nginx/.orain.org/w/maintenance/rebuildLocalisationCache.php --wiki extloadwiki > /var/log/mediawiki/rebuildLocalisationCache.log 2>&1"

- name: Download MediaWiki extensions
  command: >
            git submodule update --init
            extensions/AbuseFilter
            extensions/AdminLinks
            extensions/AntiSpoof
            extensions/ApiSandbox
            extensions/Babel
            extensions/CategoryTree
            extensions/CentralAuth
            extensions/CharInsert
            extensions/CheckUser
            extensions/Cite
            extensions/cldr
            extensions/CodeEditor
            extensions/Comments
            extensions/CreateBox
            extensions/CreateWiki
            extensions/ConfirmEdit
            extensions/Disambiguator
            extensions/DPLforum
            extensions/Echo
            extensions/Gadgets
            extensions/GlobalBlocking
            extensions/HeaderTabs
            extensions/ImageMap
            extensions/InputBox
            extensions/intersection
            extensions/Interwiki
            extensions/InterwikiMagic
            extensions/LabeledSectionTransclusion
            extensions/LiquidThreads
            extensions/MobileFrontend
            extensions/MyVariables
            extensions/Nuke
            extensions/ParserFunctions
            extensions/Poem
            extensions/Quiz
            extensions/RandomSelection
            extensions/Renameuser
            extensions/ReplaceText
            extensions/Scribunto
            extensions/SectionHide
            extensions/SimpleAntiSpam
            extensions/SiteMatrix
            extensions/SkinPerPage
            extensions/SpamBlacklist
            extensions/SyntaxHighlight_GeSHi
            extensions/Tabber
            extensions/TemplateSandbox
            extensions/Thanks
            extensions/TitleBlacklist
            extensions/Translate
            extensions/UniversalLanguageSelector
            extensions/Variables
            extensions/WikiEditor
            skins/foreground
            skins/monaco
            chdir=/usr/share/nginx/.orain.org/w
