---
- name: Check out latest stable WMF branch of MediaWiki
  git: repo=https://git.wikimedia.org/git/mediawiki/core.git
       dest=/usr/share/nginx/.orain.org/w
       version=wmf/1.22wmf12

- name: Copy MediaWiki settings from templates
  template: src={{item}} dest=/usr/share/nginx/.orain.org/w/{{item|basename|replace('.j2','')}} backup=yes
  with_fileglob:
    - ./*.php.j2
  notify: Clear APC cache

- name: Copy MediaWiki settings from files
  copy: src={{item}} dest=/usr/share/nginx/.orain.org/w/{{item|basename}} backup=yes
  with_fileglob:
    - ./*.php
  notify: Clear APC cache

- name: Download MediaWiki extensions
  command: >
            git submodule update --init
            extensions/AbuseFilter
            extensions/AntiSpoof
            extensions/CentralAuth
            extensions/CheckUser
            extensions/Cite
            extensions/ConfirmEdit
            extensions/Gadgets
            extensions/GlobalBlocking
            extensions/InputBox
            extensions/InterwikiMagic
            extensions/Nuke
            extensions/ParserFunctions
            extensions/Renameuser
            extensions/Scribunto
            extensions/SiteMatrix
            extensions/SpamBlacklist
            extensions/TitleBlacklist
            extensions/WikimediaMessages
            skins/foreground
            skins/monaco
            chdir=/usr/share/nginx/.orain.org/w

