---
- name: Check out latest stable WMF branch of MediaWiki
  git: repo=https://gerrit.wikimedia.org/r/p/mediawiki/core.git
       dest=/usr/share/nginx/.orain.org/w
       version=origin/wmf/1.22wmf9

- name: Copy MediaWiki settings from templates
  template: src={{item}} dest=/usr/share/nginx/.orain.org/w/{{item[:-3]}} backup=yes
  with_fileglob:
    - ./*.php.j2
  notify: Clear APC cache

- name: Copy MediaWiki settings from files
  copy: src={{item}} dest=/usr/share/nginx/.orain.org/w/{{item}} backup=yes
  with_fileglob:
    - ./*.php
  notify: Clear APC cache

- include: download_extension.yml item={{item}} version=REL1_21
  with_items:
    - AbuseFilter
    - CentralAuth
    - CheckUser
    - GlobalBlocking
    - WikimediaMessages
