- name: Install python-requests
  apt: pkg=python3-requests

- name: Install Composer
  action: shell curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ creates=/usr/bin/composer.phar

- name: Update Composer
  action: shell /usr/bin/composer.phar self-update
  register: composer_update_output
  changed_when: composer_update_output.stdout.find('You are already using composer version') == -1

- name: Check out latest stable WMF branch of MediaWiki
  git: repo=https://github.com/Orain/mediawiki-core.git
       dest=/usr/share/nginx/.orain.org/w
       version=REL1_23
  notify:
    - Rebuild localisation cache
    - Update mediawiki
    - Mediawiki submodule fileMode false
    - Clear APC cache