- name: Install python-requests
  apt: pkg=python3-requests

- name: Install Composer
  action: shell curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ creates=/usr/bin/composer.phar

- name: Update Composer
  action: shell /usr/bin/composer.phar self-update
  register: composer_update_output
  changed_when: composer_update_output.stdout.find('You are already using composer version') == -1
  
  # wget until we decide to set up an apt-repo. {{item}} because we have a few of these but only one exists right now
- name: wget Orain deb packages
  command: wget apt.orain.org/debian/{{item}}
  with_items:
  - php5-redis.deb
  
- name: Install Orain deb packages
  command: dpkg -i {{item}}
  with_items:
  - php5-redis.deb

- name: Check out latest stable WMF branch of MediaWiki
  git: repo=https://github.com/Orain/mediawiki-core.git
       dest=/usr/share/nginx/.orain.org/w
       version=REL1_23
  notify:
    - Rebuild localisation cache
    - Update mediawiki
    - Mediawiki submodule fileMode false
    - Clear APC cache
