- name: Ensure export directories exist
  command: mkdir -p {{item}}
  with_items:
  - /var/mediawiki/uploads
  - /var/mediawiki/private/uploads
  changed_when: False # never report as "changed"

- name: nobody owns /var/mediawiki
  command: chown nobody:nogroup /var/mediawiki/ -R

- name: Move exports over
  copy: src=exports dest=/etc/
  notify: update exports